# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

title: 学习笔记
subtitle: ''
description: ''
keywords:
author: 大脸波
language: zh-CN
timezone: ''
url: https://o0o0o0o.ml
theme: next
