# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

title: DLB's Blog
subtitle: ''
description: ''
keywords:
author: DLB
language: zh-CN
timezone: ''
url: https://o0o0o0o.ml
theme: next

search:
  path: search.xml
  field: post
  format: html
  limit: 10000
